<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report #{{ $report->report_id }} - Print</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <style>
        body { background: #f5f7fb; color: #0f172a; }
        .print-shell { max-width: 980px; margin: 28px auto; }
        .report-paper { background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 24px; }
        .brand-logo { width: 84px; height: 84px; object-fit: contain; border-radius: 8px; border: 1px solid #e2e8f0; background: #fff; padding: 6px; }
        .summary-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; background: #f8fbff; height: 100%; }
        .summary-label { font-size: 12px; color: #64748b; }
        .summary-value { font-size: 20px; font-weight: 700; }
        .comment-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; margin-bottom: 10px; background: #fff; }
        .comment-head { display: flex; justify-content: space-between; align-items: center; gap: 8px; margin-bottom: 8px; }
        .comment-meta { font-size: 12px; color: #64748b; }
        .print-tools { display: flex; gap: 8px; justify-content: flex-end; margin-bottom: 12px; }
        @media print {
            body { background: #fff; }
            .print-tools { display: none !important; }
            .print-shell { margin: 0; max-width: none; }
            .report-paper { border: 0; padding: 0; }
        }
    </style>
</head>
<body>
@php
    $logoPath = file_exists(public_path('logo-report.png')) ? asset('logo-report.png') : asset('logo.png');
@endphp
<div class="print-shell">
    <div class="print-tools">
        <a href="{{ route('admin.reports') }}" class="btn btn-outline-secondary btn-sm">Back</a>
        <button type="button" class="btn btn-primary btn-sm" onclick="window.print()"><i class="bi bi-printer me-1"></i>Print</button>
    </div>

    <div class="report-paper">
        <div class="d-flex align-items-center justify-content-between flex-wrap gap-3 mb-4">
            <div class="d-flex align-items-center gap-3">
                <img src="{{ $logoPath }}" alt="Career Insights Logo" class="brand-logo">
                <div>
                    <h4 class="mb-1">Career Insights Report</h4>
                    <div class="text-muted small">Administrative report print view</div>
                </div>
            </div>
            <div class="text-end">
                <div class="fw-semibold">Report #{{ $report->report_id }}</div>
                <div class="small text-muted">{{ $report->report_type }}</div>
                <div class="small text-muted">{{ optional($report->generated_at)->format('Y-m-d H:i') }}</div>
            </div>
        </div>

        <div class="row g-3 mb-4">
            <div class="col-md-3"><div class="summary-card"><div class="summary-label">Revenue</div><div class="summary-value">{{ number_format((float)$financialSummary['totalRevenue'], 0) }}</div><div class="small text-muted">SAR</div></div></div>
            <div class="col-md-3"><div class="summary-card"><div class="summary-label">Completed Payments</div><div class="summary-value">{{ $financialSummary['completedPayments'] }}</div></div></div>
            <div class="col-md-3"><div class="summary-card"><div class="summary-label">Evaluations</div><div class="summary-value">{{ $usageSummary['evaluations'] }}</div></div></div>
            <div class="col-md-3"><div class="summary-card"><div class="summary-label">Report Flags</div><div class="summary-value">{{ $usageSummary['reportFlags'] }}</div></div></div>
        </div>

        <div class="d-flex align-items-center justify-content-between mb-3">
            <h5 class="mb-0">Doctor Comments</h5>
            <div class="small text-muted">Generated by: {{ optional($report->admin)->department ?? '-' }}</div>
        </div>

        @forelse($doctorComments as $comment)
            <div class="comment-card">
                <div class="comment-head">
                    <div class="fw-semibold">{{ optional($comment->user)->full_name ?? 'Unknown User' }}</div>
                    <div class="comment-meta">{{ optional($comment->subMajor)->sub_major_name ?? '-' }}</div>
                </div>
                @if(!empty($comment->experience))
                    <div><strong>Experience:</strong> {{ $comment->experience }}</div>
                @endif
                @if(!empty($comment->advantages))
                    <div><strong>Advantages:</strong> {{ $comment->advantages }}</div>
                @endif
                @if(!empty($comment->disadvantages))
                    <div><strong>Disadvantages:</strong> {{ $comment->disadvantages }}</div>
                @endif
            </div>
        @empty
            <div class="text-muted">No doctor comments available.</div>
        @endforelse
    </div>
</div>
</body>
</html>
