@extends('layouts.admin')

@section('page-title', 'Reports')
@section('page-subtitle', 'Filter performance metrics and generate administrative reports')

@push('styles')
    <style>
        .reports-surface {
            border: 1px solid #dce6f8;
            box-shadow: 0 10px 24px rgba(15, 23, 42, 0.06);
        }

        .reports-surface .panel-head {
            background: #f7faff;
            border-bottom: 1px solid #e4ecfb;
        }

        .report-action-btn {
            min-width: 96px;
        }

        .report-comment-card {
            border: 1px solid #e3eaf8;
            border-radius: 8px;
            padding: 0.85rem;
            height: 100%;
            background: #fbfdff;
        }
    </style>
@endpush

@section('content')
    <x-page-header
        title="Reports"
        subtitle="Financial and usage summaries with export-ready tables"
        :breadcrumbs="[
            ['label' => 'Admin Dashboard', 'url' => route('admin.dashboard')],
            ['label' => 'Reports']
        ]"
    >
        <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#generateReportModal">
            <i class="bi bi-file-earmark-plus me-1"></i>Generate Report
        </button>
    </x-page-header>

    <div class="panel-card mb-4 reports-surface">
        <div class="panel-head d-flex align-items-center justify-content-between flex-wrap gap-2">
            <h5 class="mb-0"><i class="bi bi-funnel me-2 text-primary"></i>Report Filters</h5>
        </div>
        <div class="panel-body">
            <form method="GET" action="{{ route('admin.reports') }}" class="row g-3 align-items-end">
                <div class="col-md-4 col-lg-3">
                    <label class="form-label mb-1 small">Start Date</label>
                    <input type="date" name="start_date" class="form-control" value="{{ $startDate }}">
                </div>
                <div class="col-md-4 col-lg-3">
                    <label class="form-label mb-1 small">End Date</label>
                    <input type="date" name="end_date" class="form-control" value="{{ $endDate }}">
                </div>
                <div class="col-md-4 col-lg-4 d-flex gap-2">
                    <button class="btn btn-outline-primary" type="submit"><i class="bi bi-funnel me-1"></i>Apply Filter</button>
                    <a href="{{ route('admin.reports') }}" class="btn btn-outline-secondary">Reset</a>
                </div>
            </form>
        </div>
    </div>

    <div class="row g-4 mb-4">
        <div class="col-md-6 col-xl-3"><x-stat-card label="Revenue" :value="number_format((float)$financialSummary['totalRevenue'], 0)" suffix="SAR" icon="bi-currency-dollar" color="primary" /></div>
        <div class="col-md-6 col-xl-3"><x-stat-card label="Subscription Revenue" :value="number_format((float)$financialSummary['subscriptionRevenue'], 0)" suffix="SAR" icon="bi-journal-check" color="success" /></div>
        <div class="col-md-6 col-xl-3"><x-stat-card label="Purchase Revenue" :value="number_format((float)$financialSummary['purchaseRevenue'], 0)" suffix="SAR" icon="bi-bag-check" color="primary" /></div>
        <div class="col-md-6 col-xl-3"><x-stat-card label="Completed Payments" :value="$financialSummary['completedPayments']" icon="bi-credit-card" color="success" /></div>
        <div class="col-md-6 col-xl-3"><x-stat-card label="Subscriptions" :value="$usageSummary['subscriptions']" icon="bi-journal-bookmark" color="primary" /></div>
        <div class="col-md-6 col-xl-3"><x-stat-card label="Purchases" :value="$usageSummary['purchases']" icon="bi-cart-check" color="success" /></div>
        <div class="col-md-6 col-xl-3"><x-stat-card label="Evaluations" :value="$usageSummary['evaluations']" icon="bi-star" color="primary" /></div>
        <div class="col-md-6 col-xl-3"><x-stat-card label="Report Flags" :value="$usageSummary['reportFlags']" icon="bi-flag" color="warning" /></div>
    </div>

    <div class="row g-4">
        <div class="col-lg-6">
            <div class="panel-card h-100 reports-surface">
                <div class="panel-head"><h5 class="mb-0">Generated Reports</h5></div>
                <div class="panel-body p-0">
                    <x-data-table id="adminGeneratedReportsTable" class="table-striped" :exportable="true">
                        <thead class="table-light">
                            <tr>
                                <th>ID</th>
                                <th>Type</th>
                                <th>Generated By</th>
                                <th>Generated At</th>
                                <th class="text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($reports as $report)
                                <tr>
                                    <td>#{{ $report->report_id }}</td>
                                    <td>{{ $report->report_type }}</td>
                                    <td>{{ optional($report->admin)->department ?? '-' }}</td>
                                    <td>{{ \Carbon\Carbon::parse($report->generated_at)->format('Y-m-d H:i') }}</td>
                                    <td>
                                        <div class="d-flex justify-content-end gap-2">
                                            <button
                                                type="button"
                                                class="btn btn-sm btn-outline-primary report-action-btn js-open-comments"
                                                data-bs-toggle="modal"
                                                data-bs-target="#doctorCommentsModal"
                                                data-report-id="{{ $report->report_id }}"
                                                data-report-type="{{ $report->report_type }}"
                                            >
                                                <i class="bi bi-chat-left-quote me-1"></i>Comments
                                            </button>
                                            <a href="{{ route('admin.reports.print', $report->report_id) }}" target="_blank" class="btn btn-sm btn-primary report-action-btn">
                                                <i class="bi bi-printer me-1"></i>Print
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr><td colspan="5"><x-empty-state icon="bi-file-earmark-bar-graph" title="No generated reports" message="No reports have been generated for this period." /></td></tr>
                            @endforelse
                        </tbody>
                    </x-data-table>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel-card h-100 reports-surface">
                <div class="panel-head"><h5 class="mb-0">Payments</h5></div>
                <div class="panel-body p-0">
                    <x-data-table id="adminReportPaymentsTable" class="table-striped" :exportable="true">
                        <thead class="table-light">
                            <tr>
                                <th>Transaction</th>
                                <th>Amount</th>
                                <th>Method</th>
                                <th>Status</th>
                                <th>Date</th>
                                <th class="text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($payments as $payment)
                                <tr>
                                    <td>{{ $payment->transaction_id }}</td>
                                    <td>{{ $payment->amount }} SAR</td>
                                    <td>{{ $payment->payment_method }}</td>
                                    <td>
                                        @php($status = strtolower((string) $payment->status))
                                        <span class="badge rounded-pill {{ $status === 'completed' ? 'bg-success-subtle text-success' : ($status === 'rejected' ? 'bg-danger-subtle text-danger' : 'bg-warning-subtle text-warning') }}">
                                            {{ $payment->status }}
                                        </span>
                                    </td>
                                    <td>{{ $payment->payment_date ? \Carbon\Carbon::parse($payment->payment_date)->format('Y-m-d H:i') : '-' }}</td>
                                    <td>
                                        <div class="d-flex justify-content-end gap-2">
                                            <button type="button" class="btn btn-sm btn-outline-secondary report-action-btn" data-bs-toggle="modal" data-bs-target="#paymentDetailsModal{{ $payment->payment_id }}">
                                                <i class="bi bi-eye me-1"></i>View
                                            </button>
                                            <a href="{{ route('admin.reports.payments.print', $payment->payment_id) }}" target="_blank" class="btn btn-sm btn-primary report-action-btn">
                                                <i class="bi bi-printer me-1"></i>Print
                                            </a>
                                        </div>
                                    </td>
                                </tr>

                                <div class="modal fade" id="paymentDetailsModal{{ $payment->payment_id }}" tabindex="-1" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content border-0 shadow-sm">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Payment Details</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row g-3">
                                                    <div class="col-6"><div class="small text-muted">Payment ID</div><div class="fw-semibold">#{{ $payment->payment_id }}</div></div>
                                                    <div class="col-6"><div class="small text-muted">Transaction</div><div class="fw-semibold">{{ $payment->transaction_id ?: '-' }}</div></div>
                                                    <div class="col-6"><div class="small text-muted">Amount</div><div class="fw-semibold">{{ number_format((float)$payment->amount, 2) }} SAR</div></div>
                                                    <div class="col-6"><div class="small text-muted">Method</div><div class="fw-semibold">{{ $payment->payment_method ?: '-' }}</div></div>
                                                    <div class="col-6"><div class="small text-muted">Status</div><div class="fw-semibold">{{ $payment->status ?: '-' }}</div></div>
                                                    <div class="col-6"><div class="small text-muted">Date</div><div class="fw-semibold">{{ $payment->payment_date ? \Carbon\Carbon::parse($payment->payment_date)->format('Y-m-d H:i') : '-' }}</div></div>
                                                    <div class="col-6"><div class="small text-muted">Subscription ID</div><div class="fw-semibold">{{ $payment->subscription_id ?: '-' }}</div></div>
                                                    <div class="col-6"><div class="small text-muted">Purchase ID</div><div class="fw-semibold">{{ $payment->purchase_id ?: '-' }}</div></div>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                                                <a href="{{ route('admin.reports.payments.print', $payment->payment_id) }}" target="_blank" class="btn btn-primary">
                                                    <i class="bi bi-printer me-1"></i>Print
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <tr><td colspan="6"><x-empty-state icon="bi-credit-card" title="No payments" message="No payments found for this period." /></td></tr>
                            @endforelse
                        </tbody>
                    </x-data-table>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="generateReportModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content border-0 shadow-sm">
                <div class="modal-header">
                    <h5 class="modal-title">Generate Report</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="POST" action="{{ route('admin.reports.generate') }}">
                    @csrf
                    <div class="modal-body">
                        <div class="mb-0">
                            <label class="form-label">Report Type</label>
                            <select name="report_type" class="form-select" required>
                                <option value="">Select type</option>
                                <option value="Users Summary">Users Summary</option>
                                <option value="Subscriptions Summary">Subscriptions Summary</option>
                                <option value="Job Views Summary">Job Views Summary</option>
                                <option value="Financial Summary">Financial Summary</option>
                                <option value="Report Flags Summary">Report Flags Summary</option>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Generate</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="doctorCommentsModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content border-0 shadow-sm">
                <div class="modal-header">
                    <div>
                        <h5 class="modal-title mb-1">Summary</h5>
                        <div class="small text-muted"><span id="doctorCommentsReportRef">Report</span></div>
                    </div>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    @if(($doctorComments ?? collect())->count())
                        <div class="row g-3">
                            @foreach($doctorComments as $comment)
                                <div class="col-md-6">
                                    <div class="report-comment-card">
                                        <div class="d-flex align-items-center justify-content-between mb-2">
                                            <div class="fw-semibold">{{ optional($comment->user)->full_name ?? 'Unknown User' }}</div>
                                            <span class="badge rounded-pill bg-primary-subtle text-primary">{{ optional($comment->subMajor)->sub_major_name ?? '-' }}</span>
                                        </div>
                                        @if(!empty($comment->experience))
                                            <div class="small text-muted mb-1">Experience</div>
                                            <div class="mb-2">{{ $comment->experience }}</div>
                                        @endif
                                        @if(!empty($comment->advantages))
                                            <div class="small text-muted mb-1">Advantages</div>
                                            <div class="mb-2">{{ $comment->advantages }}</div>
                                        @endif
                                        @if(!empty($comment->disadvantages))
                                            <div class="small text-muted mb-1">Disadvantages</div>
                                            <div>{{ $comment->disadvantages }}</div>
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @else
                        <x-empty-state icon="bi-chat-left-quote" title="No comments found" message="No doctor comments are available for reporting." />
                    @endif
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var reportRef = document.getElementById('doctorCommentsReportRef');
            document.querySelectorAll('.js-open-comments').forEach(function (button) {
                button.addEventListener('click', function () {
                    if (!reportRef) {
                        return;
                    }
                    var id = button.getAttribute('data-report-id') || '-';
                    var type = button.getAttribute('data-report-type') || 'Report';
                    reportRef.textContent = 'Report #' + id + ' - ' + type;
                });
            });
        });
    </script>
@endpush
